# Generated by Django 3.0.2 on 2020-02-08 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0002_auto_20200207_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvote_users',
            field=models.ManyToManyField(related_name='Users_who_downvoted_this_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvote_users',
            field=models.ManyToManyField(related_name='Users_who_upvoted_this_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='downvote_users',
            field=models.ManyToManyField(related_name='Users_who_downvoted_this_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote_users',
            field=models.ManyToManyField(related_name='Users_who_upvoted_this_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='downvote_users',
            field=models.ManyToManyField(related_name='Users_who_downvoted_this_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvote_users',
            field=models.ManyToManyField(related_name='Users_who_upvoted_this_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
